/*
  The gate, proved on clips that fail in exactly one known way each. Every fixture is
  generated by ffmpeg at test time (tests/fixtures/review/clips.ts) and deleted after;
  a review that passed a black beat or a strobe would be worse than no review, because
  `launch` trusts it.
*/
import assert from "node:assert/strict";
import { mkdtempSync, rmSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { after, before, describe, test } from "node:test";
import {
  CELLS,
  CONFORMANCE,
  analyseFlash,
  conformTo,
  contactSheet,
  densityChecks,
  exemptGapFrames,
  flashesInWindow,
  frameAt,
  judge,
  moovBeforeMdat,
  parseRate,
  parseSilences,
  probe,
  reportText,
  reviewVideo,
  uncovered,
} from "@panoma/video-review";
import type { Probe, ReviewReport } from "@panoma/video-review";
import { makeClips } from "./fixtures/review/clips.ts";
import type { Clips } from "./fixtures/review/clips.ts";

let dir: string;
let clips: Clips;

before(() => {
  dir = mkdtempSync(join(tmpdir(), "panoma-video-review-"));
  clips = makeClips(dir);
});

after(() => {
  rmSync(dir, { recursive: true, force: true });
});

const check = (r: ReviewReport, id: string) => {
  const c = r.checks.find((c) => c.id === id);
  assert.ok(c, `no check ${id} in ${r.checks.map((c) => c.id).join(", ")}`);
  return c;
};

describe("probe", () => {
  test("reads the stream facts and the atom order", async () => {
    const p = await probe(clips.clean);
    assert.equal(p.video?.width, 320);
    assert.equal(p.video?.height, 180);
    assert.equal(p.video?.fps, 24);
    assert.equal(p.video?.codec, "h264");
    assert.equal(p.video?.profile, "High");
    assert.equal(p.video?.pixFmt, "yuv420p");
    assert.equal(p.video?.colour.primaries, "bt709");
    assert.equal(p.audio?.codec, "aac");
    assert.equal(p.audio?.sampleRate, 48000);
    assert.equal(p.audio?.channels, 2);
    assert.ok(Math.abs(p.seconds - 4) < 0.1, `duration ${p.seconds}`);
    assert.equal(p.faststart, true);
    assert.ok(p.bitrate > 0);
  });

  test("sees moov after mdat when faststart was not requested", async () => {
    assert.equal(moovBeforeMdat(clips.noFaststart), false);
    assert.equal(moovBeforeMdat(clips.clean), true);
    const p = await probe(clips.noFaststart);
    assert.equal(p.faststart, false);
  });

  test("parses frame rates the way ffprobe prints them", () => {
    assert.equal(parseRate("24/1"), 24);
    assert.ok(Math.abs((parseRate("30000/1001") ?? 0) - 29.97) < 0.01);
    assert.equal(parseRate("0/0"), undefined);
    assert.equal(parseRate(undefined), undefined);
  });
});

describe("the clean clip", () => {
  test("passes the gate with a youtube target", async () => {
    const r = await reviewVideo(clips.clean, { targets: ["youtube"] });
    const bad = r.checks.filter((c) => c.status === "fail" || c.status === "warn");
    assert.deepEqual(
      bad.map((c) => `${c.id}: ${c.summary}`),
      [],
    );
    assert.equal(r.status, "pass");
    assert.equal(r.measured.width, 320);
    assert.ok(r.measured.lufs !== undefined && r.measured.lufs > -18 && r.measured.lufs < -12, `lufs ${r.measured.lufs}`);
    assert.ok(r.measured.truePeak !== undefined && r.measured.truePeak <= -1);
    assert.ok(r.renderedAt.endsWith("Z"));
    for (const c of r.checks) assert.ok(c.summary.length > 0, `${c.id} has no summary`);
  });

  test("every non-skip check names its threshold and source", async () => {
    const r = await reviewVideo(clips.clean, { targets: ["shorts", "tiktok"] });
    for (const c of r.checks) {
      assert.ok(c.fix, `${c.id} names no fixer`);
      if (c.status === "skip") continue;
      assert.ok(c.threshold, `${c.id} has no threshold`);
      assert.ok(c.source, `${c.id} has no source`);
    }
  });
});

describe("who fixes it", () => {
  test("a failing check names its fixer; a passing one says there is nothing to do", async () => {
    const black = await reviewVideo(clips.black);
    assert.equal(check(black, "video.black").fix?.by, "record");
    assert.equal(check(black, "video.firstframe").fix?.by, "none");
    const hot = await reviewVideo(clips.hot);
    const tp = check(hot, "audio.truepeak").fix;
    assert.equal(tp?.by, "engine");
    assert.match(tp?.hint ?? "", /re-rendering will not change it — report audio\.truepeak/);
    const strobe = await reviewVideo(clips.strobe);
    assert.equal(check(strobe, "flash.bt1702").fix?.by, "engine");
    const wrong = await reviewVideo(clips.cuts, { plannedCuts: [1, 2.5] });
    assert.equal(check(wrong, "video.cuts.planned").fix?.by, "engine");
    for (const c of [...black.checks, ...hot.checks, ...strobe.checks, ...wrong.checks]) {
      assert.ok(c.fix, `${c.id} names no fixer`);
      if (c.status === "pass") assert.equal(c.fix.by, "none", `${c.id} passed but asks ${c.fix.by} to fix it`);
    }
  });

  test("words are the plan's, a hold is the recording's", () => {
    const dense = densityChecks([1, 1.5, 2, 2.5, 3, 3.5, 4], 10, 24).find((c) => c.id === "video.density");
    assert.equal(dense?.fix?.by, "plan");
    const tutorial = densityChecks([1, 2.5, 4], 6, 24, "Tutorial").find((c) => c.id === "video.asl");
    assert.equal(tutorial?.fix?.by, "plan");
  });
});

describe("video", () => {
  /* A dark interface is 98% "black" to a luma threshold: the picture checks warn, they never fail. */
  test("a black second in the middle warns, at the right second", async () => {
    const r = await reviewVideo(clips.black);
    const c = check(r, "video.black");
    assert.equal(c.status, "warn");
    assert.ok(c.at?.some((a) => Math.abs(a.seconds - 1.5) < 0.1), JSON.stringify(c.at));
    assert.equal(r.status, "warn");
  });

  test("a frozen picture warns, and passes once declared as a hold", async () => {
    const frozen = await reviewVideo(clips.frozen);
    const c = check(frozen, "video.frozen");
    assert.equal(c.status, "warn");
    assert.ok(c.at?.some((a) => Math.abs(a.seconds - 1) < 0.1), JSON.stringify(c.at));

    const held = await reviewVideo(clips.frozen, { declaredHolds: [{ from: 1, to: 3 }] });
    assert.equal(check(held, "video.frozen").status, "pass");
    assert.equal(check(held, "video.duplicates").status, "pass");
    assert.equal(held.status, "pass");
  });

  test("the first frame must show a picture", async () => {
    const r = await reviewVideo(clips.black);
    assert.equal(check(r, "video.firstframe").status, "pass");
  });

  test("planned cuts are found and unplanned ones reported", async () => {
    const r = await reviewVideo(clips.cuts, { plannedCuts: [1, 2] });
    assert.equal(check(r, "video.cuts.planned").status, "pass");
    const extra = check(r, "video.cuts.unplanned");
    assert.equal(extra.status, "warn");
    assert.ok(extra.at?.some((a) => Math.abs(a.seconds - 3) < 0.05), JSON.stringify(extra.at));
    assert.equal(r.measured.cuts, 3);

    const all = await reviewVideo(clips.cuts, { plannedCuts: [1, 2, 3] });
    assert.equal(check(all, "video.cuts.planned").status, "pass");
    assert.equal(check(all, "video.cuts.unplanned").status, "pass");

    const wrong = await reviewVideo(clips.cuts, { plannedCuts: [1, 2.5] });
    const missing = check(wrong, "video.cuts.planned");
    assert.equal(missing.status, "warn");
    assert.ok(missing.at?.some((a) => a.seconds === 2.5));
  });

  test("cut density warns under a second a shot, and slower for a tutorial", () => {
    const fast = densityChecks([1, 1.5, 2, 2.5, 3, 3.5, 4], 10, 24);
    assert.equal(fast.find((c) => c.id === "video.density")?.status, "warn");
    const fine = densityChecks([1, 3, 5, 7], 10, 24);
    assert.equal(fine.find((c) => c.id === "video.density")?.status, "pass");
    const tutorial = densityChecks([1, 2.5, 4], 6, 24, "Tutorial");
    assert.equal(tutorial.find((c) => c.id === "video.asl")?.status, "warn");
    const sales = densityChecks([1, 2.5, 4], 6, 24, "KineticQuote");
    assert.equal(sales.find((c) => c.id === "video.asl"), undefined);
  });

  test("holds subtract only the seconds they cover", () => {
    assert.equal(uncovered({ from: 1, to: 3 }, [{ from: 1, to: 3 }]), 0);
    assert.equal(uncovered({ from: 1, to: 3 }, [{ from: 2, to: 2.5 }]), 1.5);
    assert.equal(uncovered({ from: 1, to: 3 }, []), 2);
  });
});

describe("audio", () => {
  test("a file without audio skips the audio checks", async () => {
    const r = await reviewVideo(clips.silent, { expectSilent: true });
    assert.equal(check(r, "audio.stream").status, "skip");
    assert.equal(r.measured.lufs, undefined);
    assert.equal(r.status, "pass");
  });

  test("a hot file fails on true peak and clipping", async () => {
    const r = await reviewVideo(clips.hot);
    assert.equal(check(r, "audio.truepeak").status, "fail");
    assert.equal(check(r, "audio.clipping").status, "fail");
    assert.ok((r.measured.truePeak ?? -99) > -1);
  });

  test("an internal gap fails and a slow start warns", async () => {
    const gap = await reviewVideo(clips.gap);
    const c = check(gap, "audio.silence");
    assert.equal(c.status, "fail");
    assert.ok(c.at?.some((a) => Math.abs(a.seconds - 1.5) < 0.1), JSON.stringify(c.at));

    const lead = await reviewVideo(clips.lead);
    assert.equal(check(lead, "audio.silence").status, "warn");
  });

  test("silencedetect lines parse, an open silence running to the end", () => {
    const spans = parseSilences("[x] silence_start: 1.5\n[x] silence_end: 3 | silence_duration: 1.5\n[x] silence_start: 5\n", 6);
    assert.deepEqual(spans, [
      { from: 1.5, to: 3 },
      { from: 5, to: 6 },
    ]);
  });
});

describe("flash", () => {
  test("a frame-by-frame strobe fails BT.1702", async () => {
    const r = await reviewVideo(clips.strobe);
    const c = check(r, "flash.bt1702");
    assert.equal(c.status, "fail");
    assert.ok(c.at?.length);
    const flash = await analyseFlash(await probe(clips.strobe));
    assert.equal(flash.frames, 48);
    assert.ok(flash.trace[0].areaFlashing > 0.9, JSON.stringify(flash.trace));
    assert.ok(flash.trace[0].flashes > 3);
  });

  test("a change every twelve frames is exempt", async () => {
    const r = await reviewVideo(clips.exempt);
    assert.equal(check(r, "flash.bt1702").status, "pass");
    assert.equal(check(r, "flash.sustained").status, "pass");
  });

  test("the exemption gap follows the frame rate", () => {
    assert.equal(exemptGapFrames(24), 9);
    assert.equal(exemptGapFrames(25), 9);
    assert.equal(exemptGapFrames(30), 11);
    assert.equal(exemptGapFrames(60), 21);
  });

  test("three flashes a second pass and four fail, on synthetic frames", () => {
    const strobe = (period: number, seconds: number, fps: number) => {
      const frames: Uint8Array[] = [];
      for (let f = 0; f < seconds * fps; f++) {
        const on = Math.floor(f / period) % 2 === 1;
        frames.push(new Uint8Array(CELLS).fill(on ? 255 : 0));
      }
      return frames;
    };
    /* Leading edges 8 frames apart at 24 fps: 3 flashes in any second, never more. */
    assert.equal(judge(strobe(4, 3, 24), 24).checks[0].status, "pass");
    /* Leading edges 6 frames apart: 4 a second. */
    assert.equal(judge(strobe(3, 3, 24), 24).checks[0].status, "fail");
    /* Three a second over 6 s trips the IRIS warning tier, not the failure. */
    const sustained = judge(strobe(4, 7, 24), 24);
    assert.equal(sustained.checks[0].status, "pass");
    assert.equal(sustained.checks[1].status, "warn");
    /* Only a sliver of the frame flashing: area under 25%, so it passes. */
    const sliver = strobe(3, 3, 24).map((frame, i) => {
      const out = new Uint8Array(CELLS);
      for (let c = 0; c < 100; c++) out[c] = frame[c];
      return out;
    });
    assert.equal(judge(sliver, 24).checks[0].status, "pass");
  });

  test("a spaced-out run counts as no flashes in the window", () => {
    assert.equal(flashesInWindow([0, 9, 18], 0, 24, 9), 0);
    assert.equal(flashesInWindow([0, 8, 16], 0, 24, 9), 3);
    assert.equal(flashesInWindow([0, 6, 12, 18, 24], 0, 24, 9), 4);
  });
});

describe("conformance", () => {
  const fake = (over: Partial<Probe> & { seconds: number }): Probe => ({
    file: "/x.mp4",
    bytes: 10 * 1024 * 1024,
    bitrate: 9_000_000,
    container: "mov,mp4",
    faststart: true,
    video: { codec: "h264", profile: "High", width: 1080, height: 1920, fps: 24, pixFmt: "yuv420p", hasBFrames: 2, fieldOrder: "progressive", colour: { primaries: "bt709", transfer: "bt709", space: "bt709" } },
    audio: { codec: "aac", sampleRate: 48000, channels: 2, bitrate: 256_000 },
    ...over,
  });

  test("duration limits per target", () => {
    const long = fake({ seconds: 200 });
    const shorts = conformTo(long, "shorts").find((c) => c.id === "platform.shorts.duration");
    assert.equal(shorts?.status, "fail");
    assert.equal(shorts?.fix?.by, "plan");
    assert.equal(conformTo(long, "reels").find((c) => c.id === "platform.reels.duration")?.status, "warn");
    assert.equal(conformTo(long, "x").find((c) => c.id === "platform.x.duration")?.status, "fail");
    assert.equal(conformTo(long, "tiktok").find((c) => c.id === "platform.tiktok.duration")?.status, "pass");
    assert.equal(conformTo(long, "linkedin").find((c) => c.id === "platform.linkedin.duration")?.status, "pass");
    assert.equal(conformTo(fake({ seconds: 2 }), "linkedin").find((c) => c.id === "platform.linkedin.duration")?.status, "fail");
  });

  test("size, bitrate and encoding recommendations", () => {
    const huge = fake({ seconds: 30, bytes: 600 * 1024 * 1024 });
    assert.equal(conformTo(huge, "tiktok").find((c) => c.id === "platform.tiktok.size")?.status, "fail");
    /* Under YouTube's recommendation is noted, not judged: a CRF encode of flat cards
       needs fewer bits than the table assumes. Under TikTok's floor still warns. */
    const thin = fake({ seconds: 30, bitrate: 3_000_000 });
    const noted = conformTo(thin, "youtube").find((c) => c.id === "platform.youtube.bitrate");
    assert.equal(noted?.status, "pass");
    assert.match(noted?.summary ?? "", /recommends/);
    assert.equal(noted?.fix?.by, "none");
    assert.equal(conformTo(thin, "tiktok").find((c) => c.id === "platform.tiktok.bitrate")?.status, "pass");
    const starved = fake({ seconds: 30, bitrate: 2_000_000 });
    const floor = conformTo(starved, "tiktok").find((c) => c.id === "platform.tiktok.bitrate");
    assert.equal(floor?.status, "warn");
    assert.equal(floor?.fix?.by, "engine");
    const slow = fake({ seconds: 30, faststart: false });
    const enc = conformTo(slow, "youtube").find((c) => c.id === "platform.youtube.encoding");
    assert.equal(enc?.status, "warn");
    assert.match(enc?.summary ?? "", /faststart/);
    const fps = conformTo(fake({ seconds: 30 }), "linkedin").find((c) => c.id === "platform.linkedin.fps");
    assert.equal(fps?.status, "pass");
    assert.match(fps?.summary ?? "", /recommends 30/);
  });

  test("an unknown target is skipped, and every row is dated", () => {
    assert.equal(conformTo(fake({ seconds: 3 }), "vimeo")[0].status, "skip");
    for (const [name, row] of Object.entries(CONFORMANCE)) {
      assert.match(row.verified, /^\d{4}-\d{2}-\d{2}$/, name);
      assert.match(row.source, /^https:\/\//, name);
    }
  });
});

describe("pictures", () => {
  test("a contact sheet of twelve tiles stays under the image budget", async () => {
    const out = join(dir, "sheet.jpg");
    const seconds = Array.from({ length: 12 }, (_, i) => i * 0.3);
    const sheet = await contactSheet(clips.clean, { seconds, out });
    assert.equal(sheet.file, out);
    assert.equal(statSync(out).size, sheet.bytes);
    assert.ok(sheet.bytes > 0 && sheet.bytes <= 80 * 1024, `sheet is ${sheet.bytes} bytes`);
    assert.deepEqual(sheet.seconds, seconds);
  });

  test("one frame at an instant", async () => {
    const out = join(dir, "frame.jpg");
    const frame = await frameAt(clips.clean, 1.5, { out, width: 640 });
    assert.equal(frame.file, out);
    assert.ok(frame.bytes > 0 && frame.bytes <= 80 * 1024);
  });
});

describe("report text", () => {
  test("concise shows the verdict and only what needs attention; detailed shows sources", async () => {
    const r = await reviewVideo(clips.black);
    const concise = reportText(r, "concise");
    assert.match(concise, /^WARN /);
    assert.match(concise, /WARN video\.black/);
    assert.doesNotMatch(concise, /pass video\.firstframe/);
    assert.match(concise, /failed: \d+ · warned: \d+ · passed: \d+/);
    const detailed = reportText(r, "detailed");
    assert.match(detailed, /pass video\.firstframe/);
    assert.match(detailed, /source: https:\/\/ffmpeg\.org/);
  });
});
