/* Provenance describes the mounted composition, shared by automatic and Studio exports. */
import { isAbsolute, join, resolve } from "node:path";
import { expandBrief, factIds, type Brief, type FactSheet, type Provenance } from "@panoma/video-core";
import type { SessionLog } from "@panoma/video-capture";
import type { CompositionDef } from "@panoma/video-engine";
import type { ProjectProfile } from "@panoma/video-scout";
import type { ScoredTrack } from "./music.ts";
import { listFiles, readJson, type Workspace } from "./workspace.ts";

type ProvenanceInput = {
  brief: Brief;
  facts: FactSheet;
  comp: Pick<CompositionDef, "id" | "format" | "audio">;
  takes: readonly SessionLog[];
  ws: Pick<Workspace, "id" | "root" | "paths">;
  profile: Pick<ProjectProfile, "git">;
  assetsDir: string;
  engine: string;
  hasVoice: boolean;
  bedFile?: string;
  scored?: ScoredTrack;
  reviewFile: string;
  renderedAt?: string;
};

const sameFile = (a: string, b: string) => resolve(a) === resolve(b);

/** Metadata never claims a requested voice or music asset that the matrix did not mount. */
export async function exportProvenance(input: ProvenanceInput): Promise<Provenance> {
  const { brief, comp, ws } = input;
  const [, hookId, lang] = comp.id.split("--");
  const expanded = expandBrief(brief, input.facts);
  const displayed = [...brief.hooks.filter(hook => hook.id === hookId), ...brief.lines];
  const claims = displayed.map(line => ({
    line: line.id,
    text: [...expanded.hooks, ...expanded.lines].find(shown => shown.id === line.id)?.text[lang] ?? "",
    facts: [...new Set([...factIds(line.text[lang] ?? ""), ...(brief.promo?.evidence[line.id]?.facts ?? [])])],
  })).filter(claim => claim.facts.length > 0);
  const mounted = comp.audio.filter(clip => clip.volume !== 0);
  const hasAudio = (file: string | undefined) => Boolean(file && mounted.some(clip => sameFile(clip.path, file)));
  const trackFile = brief.music?.file ? (isAbsolute(brief.music.file) ? brief.music.file : join(input.assetsDir, brief.music.file)) : undefined;
  let music: Provenance["music"];
  if (hasAudio(trackFile)) {
    let scored = input.scored?.file && sameFile(input.scored.file, trackFile!) ? input.scored : undefined;
    if (!scored) for (const file of await listFiles(ws.paths.music, ".track.json")) {
      const candidate = await readJson<ScoredTrack>(file);
      if (candidate && typeof candidate.file === "string" && typeof candidate.source === "string" &&
          Number.isFinite(candidate.measured) && Number.isFinite(candidate.ratio) && sameFile(candidate.file, trackFile!)) {
        scored = candidate;
        break;
      }
    }
    music = brief.music?.prompt
      ? { source: "elevenlabs", file: trackFile, license: "See the generated track's provider terms and source credits." }
      : { source: "file", file: scored?.source ?? trackFile,
        license: scored ? "the owner's own track (brought with --music)" : "See the source track's license and credits.",
        ...(scored ? { bpm: scored.measured, stretch: scored.ratio, conformed: scored.file } : {}),
      };
  } else if (hasAudio(input.bedFile)) {
    music = { source: "procedural", file: input.bedFile, license: "AGPL-3.0-only (generated by panoma video; no third-party rights)" };
  }
  const sourceTakes = input.takes.filter(take => take.name === brief.session);
  const preferred = comp.format.id === "v" ? "mobile" : "desktop";
  const take = sourceTakes.find(take => take.take === preferred) ?? sourceTakes.find(take => take.take === (preferred === "mobile" ? "desktop" : "mobile"));
  const voice = Boolean(brief.voice && input.hasVoice && mounted.some(clip =>
    [...brief.hooks.filter(hook => hook.id === hookId), ...brief.lines].some(line =>
      sameFile(clip.path, join(ws.paths.generated, brief.id, `${line.id}-${lang}.mp3`)))));
  return {
    compositionId: comp.id, renderedAt: input.renderedAt ?? new Date().toISOString(), engine: input.engine,
    project: { id: ws.id, root: ws.root, head: input.profile.git?.head }, claims,
    takes: take ? [{ session: take.name, take: take.take, recordedAt: take.recordedAt, head: take.head, url: take.url, viewport: take.viewport,
      ...(take.videoClock ? { videoClock: take.videoClock } : {}),
    }] : [],
    ...(voice ? { voice: { provider: "elevenlabs" as const, voiceId: brief.voice!, model: "eleven_multilingual_v2", speed: brief.voiceSpeed } } : {}),
    ...(music ? { music } : {}),
    synthetic: { voice, music: music?.source === "procedural" || music?.source === "elevenlabs",
      cursor: Boolean(take && ["ProductPromo", "Tutorial", "FeatureSpotlight", "ReleaseTrailer", "ScreenCast", "ScreenDemo"].includes(brief.recipe)), broll: false },
    review: { status: "pending", file: input.reviewFile },
  };
}
