/*
  Reality in, briefs out. Git supplies the numbers; the heuristics in @panoma/video-core
  shape them; and when the `claude` CLI is on the machine, `--ai` lets a model
  rewrite the hooks — but the model only ever touches copy, never structure, and
  every failure path falls back to the heuristic draft. Drafts land in
  briefs/drafts/ and are NOT auto-registered: a human promotes them into
  briefs/index.ts, because the feed votes on hooks but a person answers for them.
*/
import { execFile } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { promisify } from "node:util";
import { draftBriefs, type Brief, type RepoStats } from "@panoma/video-core";

const run = promisify(execFile);

export async function gitStats(repo: string, days: number): Promise<RepoStats> {
  const git = (...args: string[]) => run("git", ["-C", repo, ...args]).then((r) => r.stdout.trim());
  const name = (await git("rev-parse", "--show-toplevel")).split("/").pop() ?? "project";
  const subjects = (await git("log", `--since=${days} days ago`, "--pretty=%s")).split("\n").filter(Boolean);
  const lastTag = await git("describe", "--tags", "--abbrev=0").catch(() => "");
  return { name, days, commits: subjects.length, subjects, lastTag: lastTag || undefined };
}

async function aiHooks(stats: RepoStats, drafts: Brief[]): Promise<Brief[]> {
  const prompt = [
    `You write scroll-stopping 2-second hooks for developer short-form video.`,
    `Repository: ${stats.name}. Last ${stats.days} days: ${stats.commits} commits.`,
    `Recent commit subjects:\n${stats.subjects.slice(0, 20).join("\n")}`,
    ``,
    `Return ONLY a JSON array with exactly ${drafts.length} objects, one per draft, in order.`,
    `Each object: {"en": "...", "es": "..."} — a hook under 60 characters per language.`,
    `Rules: concrete numbers beat adjectives; end sentences on their number when one appears;`,
    `no hashtags, no emoji, no quotes inside the text.`,
  ].join("\n");

  const { stdout } = await run("claude", ["-p", prompt, "--output-format", "text"], {
    timeout: 120_000,
    maxBuffer: 1024 * 1024,
  });
  const match = stdout.match(/\[[\s\S]*\]/);
  if (!match) throw new Error("no JSON array in model output");
  const hooks = JSON.parse(match[0]) as { en: string; es: string }[];
  if (hooks.length !== drafts.length) throw new Error(`expected ${drafts.length} ${drafts.length === 1 ? "hook" : "hooks"}, got ${hooks.length}`);
  return drafts.map((draft, i) => ({
    ...draft,
    hooks: [{ ...draft.hooks[0], id: `${draft.hooks[0].id}-ai`, text: hooks[i] }, ...draft.hooks],
  }));
}

export async function ideate(opts: { repo: string; days: number; ai: boolean; outDir: string }): Promise<string> {
  const stats = await gitStats(opts.repo, opts.days);
  if (stats.commits === 0) throw new Error(`No commits in the last days (${opts.days}) at ${opts.repo}.`);
  let drafts = draftBriefs(stats);
  let aiNote = "";
  if (opts.ai) {
    try {
      drafts = await aiHooks(stats, drafts);
      aiNote = " · hooks co-written by model";
    } catch (e) {
      aiNote = ` · --ai failed (${(e as Error).message.split("\n")[0]}), heuristic hooks kept`;
    }
  }

  await mkdir(opts.outDir, { recursive: true });
  const stamp = new Date().toISOString().slice(0, 10);
  const path = join(opts.outDir, `${stamp}-${stats.name}.ts`);
  const source = `/*
  Drafts from ${stats.name}: commits in the last ${stats.days} ${stats.days === 1 ? "day" : "days"}: ${stats.commits}.
  Generated by \`panoma-video ideate\`${aiNote ? aiNote.slice(3) : ""}.
  NOT auto-registered — review, edit, and move what deserves to exist into briefs/index.ts.
*/
import type { Brief } from "@panoma/video-core";

export const drafts: Brief[] = ${JSON.stringify(drafts, null, 2)};
`;
  await writeFile(path, source);
  return `${path} — drafts written: ${drafts.length}${aiNote}`;
}
