/*
  Drafts from apuntes: commits in the window (30 days): 469.
  Generated by `panoma-video ideate`--ai failed (Command failed: claude -p You write scroll-stopping 2-second hooks for developer short-form video.), heuristic hooks kept.
  NOT auto-registered — review, edit, and move what deserves to exist into briefs/index.ts.
*/
import type { Brief } from "@panoma/video-core";

export const drafts: Brief[] = [
  {
    "id": "apuntes-pace",
    "recipe": "KineticQuote",
    "langs": [
      "en",
      "es"
    ],
    "bpm": 120,
    "fps": 30,
    "hooks": [
      {
        "id": "pace",
        "text": {
          "en": "Days: 30. Commits: 469.",
          "es": "Días: 30. Commits: 469."
        }
      }
    ],
    "lines": [
      {
        "id": "what",
        "text": {
          "en": "All of it went into apuntes.",
          "es": "Todo fue a parar a apuntes."
        }
      },
      {
        "id": "why",
        "text": {
          "en": "Built in the open. No shortcuts.",
          "es": "Construido en abierto. Sin atajos."
        }
      },
      {
        "id": "brand",
        "text": {
          "en": "apuntes",
          "es": "apuntes"
        }
      }
    ],
    "tags": [
      "apuntes"
    ]
  },
  {
    "id": "apuntes-fixes",
    "recipe": "TerminalRun",
    "langs": [
      "en",
      "es"
    ],
    "bpm": 120,
    "fps": 30,
    "hooks": [
      {
        "id": "fixes",
        "text": {
          "en": "Bugs that died this week: 10",
          "es": "Bugs que murieron esta semana: 10"
        }
      }
    ],
    "lines": [
      {
        "id": "cmd",
        "text": {
          "en": "git log --oneline --since=\"30 days\"",
          "es": "git log --oneline --since=\"30 days\""
        }
      },
      {
        "id": "s0",
        "text": {
          "en": "Una regresión que metí yo, y cuatro cabos del mismo arreglo",
          "es": "Una regresión que metí yo, y cuatro cabos del mismo arreglo"
        }
      },
      {
        "id": "s1",
        "text": {
          "en": "El «no» de la persona se olvidaba si el hallazgo ya se había arreglado",
          "es": "El «no» de la persona se olvidaba si el hallazgo ya se había arreglado"
        }
      },
      {
        "id": "s2",
        "text": {
          "en": "El destilador propone dónde vale cada frase, el terminal la corrige, y la base cierra la puerta",
          "es": "El destilador propone dónde vale cada frase, el terminal la corrige, y la base cierra la puerta"
        }
      },
      {
        "id": "s3",
        "text": {
          "en": "Dónde escribir el norte, y cuántas veces le corriges",
          "es": "Dónde escribir el norte, y cuántas veces le corriges"
        }
      },
      {
        "id": "sum",
        "text": {
          "en": "Shipped fixes: 10",
          "es": "Arreglos publicados: 10"
        }
      }
    ],
    "tags": [
      "apuntes"
    ]
  }
];
